### ISSUE TITLE
Need a release tag created to add a Homebrew formula

### ISSUE THREAD

**Issue by dlackty** [alloy/watch-sim#7]
Hello, @alloy!
Just made a Homebrew formula for this nice little utility. However, just like CocoaPods does, Homebrew formula also requires a git version tag. Could you please push a tag?

Thanks in advance! :+1:

**Comment by alloy** [comment]
@dlackty Thanks for that! Yup, pushed 1.0.0 https://github.com/alloy/watch-sim/tree/1.0.0.

Please link the homebrew PR here for my reference :)

**Comment by dlackty** [comment]
Just sent the pull request. Hope it could get merged soon :)

**Comment by alloy** [comment]
Thanks!
